src/test/java/org/github/_1c_syntax/bsl/languageserver/BSLLSPLauncherTest.java
src/test/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/ConsoleReporterTest.java
src/test/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/ReportersAggregatorTest.java

Тесты обязательно починятся, когда станет понятно как тестить логер.

volkswagen mode on

---

build.gradle.kts
docs/index.md
src/main/java/org/github/_1c_syntax/bsl/languageserver/BSLLSPLauncher.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/cli/AnalyzeCommand.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/AbstractDiagnosticReporter.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/ConsoleReporter.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/GenericIssueReporter.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/JUnitReporter.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/JsonReporter.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/ReportersAggregator.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/TSLintReporter.java
src/test/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/GenericReporterTest.java
src/test/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/JUnitReporterTest.java
src/test/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/ReportersAggregatorTest.java

* каталог отчетов reportDir
* абстрактный класс вместе интерфейса

WIP Каталог экспорта отчетов (базовая версия)

---

src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/FunctionShouldHaveReturnDiagnostic.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/metadata/DiagnosticMetadata.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/GenericIssueReport.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/providers/DiagnosticProvider.java

* Добавлено timeToFix в DiagnosticMetadata
* Добавлено получение timeToFix по BSLDiagnostic и экспорт в формате GenericIssue

WIP: Проба timeToFix

---

src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/CanonicalSpellingKeywordsDiagnostic.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/EmptyCodeBlockDiagnostic.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/EmptyStatementDiagnostic.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/FunctionShouldHaveReturnDiagnostic.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/IfElseDuplicatedCodeBlockDiagnostic.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/IfElseDuplicatedConditionDiagnostic.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/IfElseIfEndsWithElseDiagnostic.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/LineLengthDiagnostic.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/MethodSizeDiagnostic.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/NestedTernaryOperatorDiagnostic.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/NumberOfOptionalParamsDiagnostic.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/NumberOfParamsDiagnostic.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/OneStatementPerLineDiagnostic.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/OrderOfParamsDiagnostic.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/SelfAssignDiagnostic.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/SemicolonPresenceDiagnostic.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/UnknownPreprocessorSymbolDiagnostic.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/UsingCancelParameterDiagnostic.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/YoLetterUsageDiagnostic.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/providers/DiagnosticProvider.java
src/test/java/org/github/_1c_syntax/bsl/languageserver/providers/DiagnosticProviderTest.java

WIP: Заполнение minutes to fix у диагностик

---

docs/en/index.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/8681)

Translate index.md via GitLocalize

---

docs/en/reporters/tslint.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/8697)

Translate tslint.md via GitLocalize

---

docs/en/reporters/json.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/8696)

Translate json.md via GitLocalize

---

docs/en/diagnostics/UsingCancelParameter.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/8693)

Translate UsingCancelParameter.md via GitLocalize

---

docs/en/reporters/console.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/8695)

Translate console.md via GitLocalize

---

docs/en/diagnostics/YoLetterUsage.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/8694)

Translate YoLetterUsage.md via GitLocalize

---

docs/en/diagnostics/UnknownPreprocessorSymbol.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/8692)

Translate UnknownPreprocessorSymbol.md via GitLocalize

---

docs/en/diagnostics/SelfAssign.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/8690)

Translate SelfAssign.md via GitLocalize

---

docs/en/diagnostics/SemicolonPresence.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/8691)

Translate SemicolonPresence.md via GitLocalize

---

docs/en/diagnostics/ProcedureReturnsValue.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/8689)

Translate ProcedureReturnsValue.md via GitLocalize

---

docs/en/diagnostics/OrderOfParams.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/8688)

Translate OrderOfParams.md via GitLocalize

---

docs/en/diagnostics/OneStatementPerLine.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/8687)

Translate OneStatementPerLine.md via GitLocalize

---

docs/en/diagnostics/IfElseIfEndsWithElse.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/8684)

Translate IfElseIfEndsWithElse.md via GitLocalize

---

docs/en/diagnostics/IfElseDuplicatedCondition.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/8683)

Translate IfElseDuplicatedCondition.md via GitLocalize

---

docs/en/diagnostics/CanonicalSpellingKeywords.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/8679)

Translate CanonicalSpellingKeywords.md via GitLocalize

---

docs/en/diagnostics/EmptyStatement.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/8677)

Translate EmptyStatement.md via GitLocalize

---

docs/en/diagnostics/FunctionShouldHaveReturn.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/8678)

Translate FunctionShouldHaveReturn.md via GitLocalize

---

docs/en/diagnostics/EmptyCodeBlock.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/8676)

Translate EmptyCodeBlock.md via GitLocalize

---

docs/en/diagnostics/IfElseDuplicatedCodeBlock.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/8682)

Translate IfElseDuplicatedCodeBlock.md via GitLocalize

---

docs/en/diagnostics/LineLength.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/8704)

Translate LineLength.md via GitLocalize

---

src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/NumberOfValuesInStructureConstructorDiagnostic.java
src/test/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/NumberOfValuesInStructureConstructorDiagnosticTest.java
src/test/resources/diagnostics/NumberOfValuesInStructureConstructorDiagnostic.bsl

Fix:Исправлена ошибка в случае, когда структура объявлена без явного вызова конструктора

---

docs/en/diagnostics/DeprecatedMessage.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/8849)

Translate DeprecatedMessage.md via GitLocalize

---

docs/en/diagnostics/UsingServiceTag.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/8852)

Translate UsingServiceTag.md via GitLocalize

---

src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/EmptyCodeBlockDiagnostic.java

Упадет при добавлении tryCodeBlock
После можно мерджить https://github.com/1c-syntax/bsl-parser/pull/33

Исправление для новой грамматики

---

src/main/java/org/github/_1c_syntax/bsl/languageserver/BSLTextDocumentService.java

DidClose возвращает пустые диагностики #193

---

README.md
docs/en/index.md
docs/index.md
src/main/java/org/github/_1c_syntax/bsl/languageserver/BSLLSPLauncher.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/cli/VersionCommand.java
src/test/java/org/github/_1c_syntax/bsl/languageserver/cli/VersionCommandTest.java

fix #176 version command

---

src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/AbstractListenerDiagnostic.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/AbstractVisitorDiagnostic.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/DeprecatedMessage.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/DiagnosticStorage.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/utils/RangeHelper.java

Fix #208 AbstractListenerDiagnostic

---

src/main/java/org/github/_1c_syntax/bsl/languageserver/context/DocumentContext.java

#218 убираем выхлоп парсера в консоль

---

docs/en/diagnostics/TryNumber.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/8920)

Translate TryNumber.md via GitLocalize

---

docs/en/diagnostics/ParseError.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/8971)

Translate ParseError.md via GitLocalize

---

docs/en/diagnostics/NestedStatements.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/8970)

Translate NestedStatements.md via GitLocalize

---

src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/NestedConstructorsInStructureDeclarationDiagnostic.java
src/test/resources/diagnostics/NestedConstructorsInStructureDeclarationDiagnostic.bsl

fp new array() fix

---

src/main/resources/org/github/_1c_syntax/bsl/languageserver/diagnostics/FunctionShouldHaveReturnDiagnostic_en.properties
src/main/resources/org/github/_1c_syntax/bsl/languageserver/diagnostics/IfElseIfEndsWithElseDiagnostic_en.properties
src/main/resources/org/github/_1c_syntax/bsl/languageserver/diagnostics/NestedStatementsDiagnostic_en.properties
src/main/resources/org/github/_1c_syntax/bsl/languageserver/diagnostics/ProcedureReturnsValueDiagnostic_en.properties
src/main/resources/org/github/_1c_syntax/bsl/languageserver/diagnostics/SemicolonPresenceDiagnostic_en.properties
src/main/resources/org/github/_1c_syntax/bsl/languageserver/diagnostics/TryNumberDiagnostic_en.properties
src/main/resources/org/github/_1c_syntax/bsl/languageserver/diagnostics/YoLetterUsageDiagnostic_en.properties

Функция должна содержать возврат
Должна - как обязана

изменение текста сообщения и описание диагностик

---

src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/EmptyStatementDiagnostic.java
src/main/resources/org/github/_1c_syntax/bsl/languageserver/diagnostics/EmptyStatementDiagnostic_en.properties
src/main/resources/org/github/_1c_syntax/bsl/languageserver/diagnostics/EmptyStatementDiagnostic_ru.properties

EmptyStatement QuickFix 

---

src/main/java/org/github/_1c_syntax/bsl/languageserver/providers/FoldingRangeProvider.java
src/test/java/org/github/_1c_syntax/bsl/languageserver/providers/FoldingRangeProviderTest.java
src/test/resources/providers/foldingRangeParseError.bsl

FoldinRangeProvider fix

---

docs/en/diagnostics/UseLessForEach.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/8976)

Translate UseLessForEach.md via GitLocalize

---

src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/metadata/DiagnosticMetadata.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/providers/DiagnosticProvider.java

По умолчанию все диагностики - активные

#192 Свойство диагностики ActivatedByDefault

---

docs/en/diagnostics/NestedTernaryOperator.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/9417)

Translate NestedTernaryOperator.md via GitLocalize

---

docs/en/diagnostics/IdenticalExpressions.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/9494)

Translate IdenticalExpressions.md via GitLocalize

---

docs/en/reporters/junit.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/9493)

Translate junit.md via GitLocalize

---

docs/en/reporters/generic.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/9492)

Translate generic.md via GitLocalize

---

src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/PairingBrokenTransactionDiagnostic.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/SeveralCompilerDirectivesDiagnostic.java
src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/GenericIssueReporter.java
src/test/java/org/github/_1c_syntax/bsl/languageserver/BSLTextDocumentServiceTest.java
src/test/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/IfElseDuplicatedConditionDiagnosticTest.java
src/test/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/NumberOfValuesInStructureConstructorDiagnosticTest.java

После оптимизации импорта в IDEA изменяется ряд файлов проекта.
Fixes #342

#342 After Optimizing imports some project files are modified

---

src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/SeveralCompilerDirectivesDiagnostic.java
src/test/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/SeveralCompilerDirectivesDiagnosticTest.java

#340
Скорректировал позиционирование замечания

fix bug #340

---

build.gradle.kts

Добавил в зависимости javax.xml.bind  jaxb-api

---

docs/en/diagnostics/CognitiveComplexity.md

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/10414)

Translate CognitiveComplexity.md via GitLocalize

---

README.md
build.gradle.kts
docs/en/index.md
docs/index.md
src/main/java/com/github/_1c_syntax/bsl/languageserver/BSLLSPLauncher.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/cli/FormatCommand.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/providers/FormatProvider.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/BSLLSPLauncherTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/cli/FormatCommandTest.java

Fix #346 Массовое форматирование через CLI

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/UsingHardcodePathDiagnostic.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/UsingHardcodePathDiagnosticTest.java

Упрощена работа с параметрами конфигурации в диагностике. + тесты на параметры конфигурации

Доработка тестов диагностики UsingHardcodePathDiagnostic

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/JUnitTestSuites.java

Замечание https://sonarcloud.io/project/issues?id=1c-syntax_bsl-language-server&issues=AW2M8Hfre8I6Y7cJZrXj&open=AW2M8Hfre8I6Y7cJZrXj

Исправление замечания сонара

---

gradle/tools-new-diagnostic.gradle.kts

По следам стрима изменил табы на пробелы - вроде как это правильнее )

Изменил табы на пробелы в gradle newDiagnostic

---

docs/en/diagnostics/NumberOfOptionalParams.md
src/main/resources/org/github/_1c_syntax/bsl/languageserver/diagnostics/NumberOfOptionalParamsDiagnostic_en.properties

[Check out a review request at GitLocalize](https://gitlocalize.com/repo/1840/en/review/9422)

Translate NumberOfOptionalParams.md via GitLocalize

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/Trees.java

1. Исправил ошибку поиска предыдущей ноды - искал только с тем же типом, что и основная
2. Добавил поиск следующей ноды
#243

Исправление ошибки в методах Trees

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/context/DocumentContext.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/context/computer/CognitiveComplexityComputer.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/BeginTransactionBeforeTryCatchDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CommitTransactionOutsideTryCatchDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/DeletingCollectionItemDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/EmptyCodeBlockDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/FunctionShouldHaveReturnDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/IfConditionComplexityDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/NestedConstructorsInStructureDeclarationDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/NestedTernaryOperatorDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/PairingBrokenTransactionDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ProcedureReturnsValueDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/SelfAssignDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/SeveralCompilerDirectivesDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TryNumberDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/UnreachableCodeDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/UseLessForEachDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/UsingCancelParameterDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/providers/FoldingRangeProvider.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/Trees.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/UnreachableCodeDiagnosticTest.java

Добавил в utils.Trees обетки antlr.Trees и скорректировал импорты
#519

Перевел на использование оберток

---

.github/workflows/gh-pages.yml

Valery Maximov:
Если на странице https://1c-syntax.github.io/bsl-language-server/dev/en/ ткнуть в russian уходит на https://1c-syntax.github.io/bsl-language-server/

Patch Develop in gh-pages.yml workflow

---

src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/SmokyTest.java

Дымой тест - выполняет диагностику всех файлов ресурсов.
Closes: #404

Дымовой тест - NPE в диагностиках

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/BSLLanguageServer.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/configuration/LanguageServerConfiguration.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/context/ServerContext.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/context/ServerContextTest.java

rooturi cast to Path правильно?

---

build.gradle.kts
src/main/java/com/github/_1c_syntax/bsl/languageserver/providers/DiagnosticProvider.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/providers/DiagnosticProviderTest.java

en description in resources

---

build.gradle.kts

mdclasses немного урезана. Теперь ее размер меньше.

Бамп версии mdclasses

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/BeginTransactionBeforeTryCatchDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CognitiveComplexityDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CommentedCodeDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CommitTransactionOutsideTryCatchDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/InvalidCharacterInFileDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingSpaceDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MultilingualStringHasAllDeclaredLanguagesDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/OneStatementPerLineDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/UnusedLocalMethodDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/UsingThisFormDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/WorkingTimeoutWithExternalResourcesDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/MultilingualStringAnalyser.java

Внесены исправления по сонару
- CommentedCodeDiagnostic: удалено магическое число, константная строка вынесена
- WorkingTimeoutWithExternalResourcesDiagnostic: сокращено количество возвратов
- UsingThisFormDiagnostic: пометил закомментированный код как туду
- WorkingTimeoutWithExternalResourcesDiagnostic: исправил опечатки, оптимизировал условия, обыграл маловероятный NPE
- BeginTransactionBeforeTryCatchDiagnostic: оптимизация цикломатической сложности
- CommentedCodeDiagnostic: магические числа
- CommitTransactionOutsideTryCatchDiagnostic: оптимизация цикломатической сложности
- InvalidCharacterInFileDiagnostic: явное указание типов
- MultilingualStringHasAllDeclaredLanguagesDiagnostic: убрал табы
- OneStatementPerLineDiagnostic: поменял местами final и static
- …

Патчи для сонара

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/context/DocumentContext.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/context/computer/CognitiveComplexityComputer.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/context/symbol/RegionSymbol.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/metadata/DiagnosticInfo.java

* добавлено интернирование часто встречающихся строк - при чтении ресурсов, сообщения диагностик и текстов данных когнитивной сложности
* добавлена очистка всех областей документа, а не только верхнего уровня
* исправлена очистка данных AST для RegionSymbol - удалялись не все ссылки на узлы AST, как следствие AST не выгружалось их памяти
Closes: #627

Снижение потребления памяти

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/AnalysisInfo.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/GenericIssueReport.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/GenericIssueReporter.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/GenericReporterTest.java

Исправил формирование путей в generic отчете с абсолютных на относительные
Closes: #557

Исправление ошибки при генерации generic отчета

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/DiagnosticSupplier.java

getDiagnisticClasses теперь статик
Closes: #639

make getDiagnosticClasses static

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/DeletingCollectionItemDiagnostic.java

Убран lowercase при формировании сообщения диагностики DeletingCollectionItem
Closes: #670

Убран lowercase при формировании сообщения диагностики DeletingCollectionItem

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/NestedStatementsDiagnostic.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/NestedStatementsDiagnosticTest.java

Вернул считывание параметра из настроек
Closes: #701

Поправил считывание параметра в NestedStatementsDiagnostic

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/DiagnosticSupplier.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/DiagnosticSupplierTest.java

Исправлен фильтр по режиму совместимости
Closes: #700

fix Compatibility #700

---

build.gradle.kts
src/main/java/com/github/_1c_syntax/bsl/languageserver/cli/AnalyzeCommand.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/cli/FormatCommand.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/configuration/LanguageServerConfiguration.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/context/DocumentContext.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/context/ServerContext.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/FileInfo.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/providers/CodeActionProvider.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/providers/DiagnosticProvider.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/Absolute.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/RelatedInformation.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/BSLLanguageServerTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/BSLTextDocumentServiceTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/configuration/LanguageServerConfigurationTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/context/ServerContextTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/AbstractDiagnosticTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/EmptyStatementDiagnosticTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/InvalidCharacterInFileDiagnosticTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingSpaceDiagnosticTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/OneStatementPerLineDiagnosticTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/SemicolonPresenceDiagnosticTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/SpaceAtStartCommentDiagnosticTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/JUnitReporterTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/providers/CodeActionProviderTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/providers/FoldingRangeProviderTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/providers/FormatProviderTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/util/TestUtils.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/util/assertions/CodeActionAssert.java

* Работа DocumentContext переведена на URI
* Везде применяются абсолютные каноникализированные пути
* Исправлено определение ModuleType в VSC
Closes: #733

Использование абсолютно абсолютных путей

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/DeletingCollectionItemDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/OrderOfParamsDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TryNumberDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/UseLessForEachDiagnostic.java

Почистил код некоторых диагностик
+ [x] Ветка PR обновлена из develop
+ [x] Отладочные, закомментированные и прочие, не имеющие смысла участки кода удалены
+ [x] Изменения покрыты тестами
+ [x] Обязательные действия перед коммитом выполнены (запускал команду `gradlew precommit`)

Some diagnostic fixes

---

jitpack.yml

jipack.yml

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CompilationDirectiveLostDiagnostic.java

Исправление сообщения в диагностике 
Closes: #741

message fix

---

gradle/tools-update-json-schema.gradle.kts
src/main/resources/com/github/_1c_syntax/bsl/languageserver/configuration/diagnostics-schema.json

Исправлена ошибка генерации схемы после переезда на ресурсы
Closes:

Исправлена ошибка генерации схемы после переезда на ресурсы

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/EmptyRegionDiagnostic.java
src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/EmptyRegionDiagnostic_en.properties
src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/EmptyRegionDiagnostic_ru.properties
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/EmptyRegionDiagnosticTest.java

Closes:
- [+] Ветка PR обновлена из develop
- [+] Отладочные, закомментированные и прочие, не имеющие смысла участки кода удалены
- [+] Изменения покрыты тестами
- [+] Обязательные действия перед коммитом выполнены (запускал команду `gradlew precommit`)
- [+] Описание диагностики заполнено для обоих языков (перевод на английский не обязателен)

EmptyRegionDiagnostic. Quick Fix implementation.

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/context/DocumentContext.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/context/computer/MethodSymbolComputer.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/context/symbol/MethodSymbol.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/EmptyRegionDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/NonExportMethodsInApiRegionDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/providers/DocumentSymbolProvider.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/Lazy.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/context/DocumentContextTest.java

Теперь RegionSymbol внутри MethodSymbol обернут в Optional вместо nullable-поля.
Исправлен алгоритм проверки на доуточнение данных области и методов.
Closes: #749

Рефакторинг работы с областями

---

gradle/developer-tools.gradle.kts

Изменен алгоритм загрузки классов для получения информации о диагностиках - вместо jar файла анализируются собранные классы
Closes: #767

Исправление привнесенной ошибки утилит разработчика

---

.github/workflows/release.yml

В рамках задачи #693
Умеет: собирать по трем ос (win, ubuntu, macos) app image и прикреплять к релизу.

Сборка app image и публикация в релизе через GA

---

docs/contributing/EnvironmentSetting.md

Добавил ссылку на настройку SDK в русскую документацию и чуть поправил отступы, чтоб правильно отображалось на сайте

Ссылка в документации на настройку SDK

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/metadata/DiagnosticInfo.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/metadata/DiagnosticInfoTest.java

Северити на Тайп для lsp Северити

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/configuration/LanguageServerConfiguration.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/context/symbol/MethodDescription.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/FormDataToValueDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/GetFormMethodDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingSpaceDiagnostic.java

По сонару небольшие правки
- магические числа
- именование
Closes:

По сонару небольшие правки

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/configuration/LanguageServerConfiguration.java

предлагаю такое исправление подробнее #799 
Closes #799

поправил формирование пули для EDT формата конфигураций

---

build.gradle.kts
src/main/java/com/github/_1c_syntax/bsl/languageserver/context/computer/MethodSymbolComputer.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/context/DocumentContextTest.java

Теперь несколько WHITESPACE подряд группируются в один

Переезд на новый парсер и изменненой логикой подсчета WHITESPACE

---

.github/workflows/gh-pages.yml
mkdocs.en.yml
mkdocs.yml

Переложил схему поближе к корню плюс добавил разделы
Closes: #814

Правки в формировании сайта

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/AbstractFindMethodDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/DeprecatedFindDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/DeprecatedMessageDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/FormDataToValueDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/GetFormMethodDiagnostic.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/DeprecatedMessageDiagnosticTest.java

Вынос общей логики поиска методов в абстрактную диагностику
Close #829 
- [+] Ветка PR обновлена из develop
- [+] Отладочные, закомментированные и прочие, не имеющие смысла участки кода удалены
- [] Изменения покрыты тестами
- [+] Обязательные действия перед коммитом выполнены (запускал команду `gradlew precommit`)

Abstract find method diagnostic

---

gradle/tools-new-diagnostic.gradle.kts

Сменил таб на пробел
Closes: #881

Исправление ошибки в задаче Gradle NewDiagnostic

---

docs/en/diagnostics/MultilingualStringHasAllDeclaredLanguages.md
docs/en/diagnostics/MultilingualStringUsingWithTemplate.md

Исправлены битые ссылки в документации
Closes: #884

Исправлены битые ссылки в документации

---

.idea/jarRepositories.xml
build.gradle.kts

Обновление mdclasses

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/NonStandardRegionDiagnostic.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/NonStandardRegionDiagnosticTest.java

fp NonStandardRegion на область

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CodeOutOfRegionDiagnostic.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CodeOutOfRegionDiagnosticTest.java

Убран нулевой регион
Closes: #911

CodeOutOfRegionDiagnostic. Убран нулевой регион

---

src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/SmokyTest.java

Добавлен тест всех диагностик на всех файлах на предмет падения
Closes: #917

Тест всех диагностик на падения

---

src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/SmokyTest.java

Вынес создание провайдера из цикла
Closes: #919

Ускорение дымового теста

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/providers/DiagnosticProvider.java

Получение диагностик в DiagnosticSupplier обернуто в попытку.
Closes: #931

Безопасный расчет диагностик

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/context/DocumentContext.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/context/DocumentContextTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/util/TestUtils.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/utils/AbsoluteTest.java

Более аккуратная работа с uri и path, приходящим от клиента
Closes: #929

Поддержка работы BSL LS с документами с untitled-схемой

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/NonStandardRegionDiagnostic.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/NonStandardRegionDiagnosticTest.java

1. Добавил в список разрешенных областей модуля набора записей область инициализации;
2. Покрыл изменение тестами
Closes #921

Расширил список разрешенных областей модуля набора записей

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/Absolute.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/utils/AbsoluteTest.java

Декодирование URI без использования Path
Closes: #934

#934 Обработка uri, содержащих имя сервера

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CodeBlockBeforeSubDiagnostic.java

Исправление ошибки обработки несуществующего на самом деле узла
Closes: #963

Исправление ошибки обработки несуществующего на самом деле узла

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/UnaryPlusInConcatenationDiagnostic.java

Перенес поиск предыдущей ноды во вложенное условие
Closes:

микро оптимизация диагностики

---

build.gradle.kts
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TypoDiagnostic.java

Тяжеловесные JLanguageTool-объекты инициализируются только, если диагностика включена

Оптимизация TypoDiagnostic

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/AbstractMultilingualStringDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/MultilingualStringAnalyser.java

Создание исключения вылазило при профайленге не на очень высоких позициях.

Убрал исключение 

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TypoDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/typo/JLanguageToolPool.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/typo/JLanguageToolPoolEntry.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/AbstractObjectPool.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/JLanguageToolPool.java

JavaDoc подсказывает нам, что Language нужно создавать один на приложение, а LangTool - один на поток

Оптимизация использования объектов JLanguageTool

---

.idea/inspectionProfiles/Project_Default.xml
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/BSLDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CognitiveComplexityDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CyclomaticComplexityDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/DiagnosticSupplier.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/EmptyCodeBlockDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/IfConditionComplexityDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/LineLengthDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MagicNumberDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MethodSizeDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingCodeTryCatchExDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingSpaceDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/NestedStatementsDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/NumberOfOptionalParamsDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/NumberOfParamsDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/NumberOfValuesInStructureConstructorDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/PublicMethodsDescriptionDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TimeoutsInExternalResourcesDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TooManyReturnsDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TypoDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/DiagnosticHelper.java

1. В DiagnosticSupplier в configureDiagnostic реализовал заполнение примитивных параметров пере вызово конфигурирования из диагностии
2. В абстрактный класс тестов добавил метод получения сконфигурироанного инстанс диагности
Closes: #462

WIP Автоматическое конфигурирование диагностики

---

docs/assets/stylesheets/extra.css
mkdocs.en.yml
mkdocs.yml

Описание изменений релиза: https://squidfunk.github.io/mkdocs-material/releases/5/
Поправил настроечные файлы и css, т.к. содержание поехало

Обновления под mkdocs material 5.0

---

docs/assets/stylesheets/extra.css

Отступ заголовка содержания в mcdocs

---

docs/contributing/index.md

- Добавил ссылку
Closes: #1048

В Руководство контрибьютора нет ссылки на полезную статью "Структура диагностики, назначение и содержимое файлов"

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/UsingServiceTagDiagnostic.java

- Идея выдает замечание
- ![image](https://user-images.githubusercontent.com/2920817/79073114-601f9f80-7ced-11ea-8c34-0622bf7bac97.png)
- посмотрел код, а там двойная проверка строки на регулярку
- в итоге убрал двойную проверку, правило должно ускориться.
Closes:
связанного ишуза нет, т.к. это исправление сразу в виде ПР, вроде как тех.долг.
если нужно, могу создать ишуз.

Убрал ненужный дубль проверки строки на регулярку - обработка замечания от инспекции Идеи

---

docs/en/diagnostics/MethodSize.md
docs/en/diagnostics/index.md
src/main/resources/com/github/_1c_syntax/bsl/languageserver/configuration/diagnostics-schema.json

Пропущенные результаты precommit - т.к. при его выполнении правильно удаляется лишний пробел

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/DataExchangeLoadingDiagnostic.java

Issue1079 / Фикс регулярки + map to flatmap (избавился от get)

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/configuration/LanguageServerConfiguration.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TimeoutsInExternalResourcesDiagnostic.java

В регулярках использование точки опасно.
Closes:
Связанного ишуза нет, т.к. это небольшой тех.долг.

Неточные регулярки - неточное использование точки

---

docs/diagnostics/ConsecutiveEmptyLines.md
docs/en/diagnostics/ConsecutiveEmptyLines.md
gradle/developer-tools.gradle.kts
src/main/java/com/github/_1c_syntax/bsl/languageserver/BSLTextDocumentService.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/configuration/Language.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/configuration/LanguageServerConfiguration.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/configuration/codelens/CodeLensOptions.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/configuration/codelens/package-info.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/configuration/diagnostics/ComputeTrigger.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/configuration/diagnostics/DiagnosticsOptions.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/configuration/diagnostics/Language.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/configuration/diagnostics/Mode.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/configuration/diagnostics/SkipSupport.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/configuration/diagnostics/databind/ParametersDeserializer.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/configuration/diagnostics/databind/RulesDeserializer.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/configuration/diagnostics/package-info.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/configuration/package-info.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/DiagnosticSupplier.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/metadata/DiagnosticInfo.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/GenericIssueReport.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/providers/CodeLensProvider.java
src/main/resources/com/github/_1c_syntax/bsl/languageserver/configuration/parameters-schema.json
src/main/resources/com/github/_1c_syntax/bsl/languageserver/configuration/schema.json
src/test/java/com/github/_1c_syntax/bsl/languageserver/configuration/LanguageServerConfigurationTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/DiagnosticSupplierTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/SmokyTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/metadata/DiagnosticInfoTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/providers/CodeActionProviderTest.java
src/test/resources/.bsl-language-server.json

WIP: Рефакторинг конфигурации. DiagnosticsMode

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/BSLLSPLauncher.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/BSLLSPLauncherTest.java

добавил обработку переданного параметра в команду по умолчанию
Closes:

Fix PicoCli default command

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ExcessiveAutoTestCheckDiagnostic.java
src/test/resources/diagnostics/ExcessiveAutoTestCheckDiagnostic.bsl

Небольшой рефакторинг по мотивам https://github.com/1c-syntax/bsl-language-server/pull/1097#discussion_r412051666

Рефакторинг обращения к токинам

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/DeprecatedMethods8310Diagnostic.java

Перенесен конструктор и переменные согласно Code Conventions
Closes: #1134

Добавлено явное указание локалей при вызове toLowerCase()

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/metadata/DiagnosticCompatibilityMode.java

Добавлен новый режим совместимости: 8.3.17
Closes: #1142

Новый режим совместимости: 8.3.17

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/context/DocumentContext.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/EmptyRegionDiagnostic.java

Чистка кода
- [+ ] Ветка PR обновлена из develop
- [+ ] Отладочные, закомментированные и прочие, не имеющие смысла участки кода удалены

Some cleanups.

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/UnsafeSafeModeMethodCallDiagnostic.java

Исправление замечания:
https://sonarcloud.io/project/issues?assignees=EightM%40github&createdAfter=2020-04-28&id=1c-syntax_bsl-language-server&open=AXHGdXvko2Q3nzySnRlH&resolved=false

Исправление замечаний сонара

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/EmptyRegionDiagnostic.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/EmptyRegionDiagnosticTest.java

Переписал диагностику
Только диагностику, квик фиксы походу были поломаны и до меня)
Тест на квикфиксы закомментирован, т.к. непонятно как должно происходить взаимодействие с IDE. Можно поломать лишнее.

Cleanup diagnostic for EmptyRegion

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/BSLLanguageServer.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/cli/AnalyzeCommand.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/context/DocumentContext.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/context/ServerContext.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/context/ServerContextTest.java

Двойной проход файлов для наполнения базы контекстов

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/SemicolonPresenceDiagnostic.java

Диагностика SemicolonPresence. Перенос проверки внутрь дает прирост с 3000 до 725
Closes:

SemicolonPresence проверка на разбор перенесена внутрь

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/context/ServerContext.java

Добавлена синхронизация на операциях наполнения контекста
Closes: #1228

RW-lock для синхронизации между наполнением контекста и работой ServerContext

---

build.gradle.kts
src/main/java/com/github/_1c_syntax/bsl/languageserver/context/ServerContext.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/context/computer/MethodSymbolComputer.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CommonModuleAssignDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/NonStandardRegionDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/MdoRefBuilder.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/context/computer/VariableSymbolTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/DiagnosticSupplierTest.java

Обновлена зависимость от mdclasses + патчи для поддержки изменений
Closes: #1238

Обновлена версия mdclasses

---

build.gradle.kts

Обновлена зависимость mdclasses
Closes:

Обновлена зависимость mdclasses

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingSpaceDiagnostic.java

Отказ от регулярок в пользу поиска в Set.
Замеры прироста производительности - с ~1850 до ~850
Closes: #1236

Оптимизация MissingSpace 2

---

src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MetadataObjectNameLengthDiagnosticTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/UsingSynchronousCallsDiagnosticTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/util/TestApplicationContext.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/util/TestUtils.java

WIP: spring boot try fix tests

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/AbstractCommonModuleNameDiagnostic.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CommonModuleNameClientDiagnosticTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CommonModuleNameClientServerDiagnosticTest.java

CommonModulesName приведен к стандарту

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CommonModuleNameCachedDiagnostic.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CommonModuleNameCachedDiagnosticTest.java

Исправил опечатку
Closes: #1315

fix CommonModuleNameCached

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/BSLLanguageServer.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/BSLWorkspaceService.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/context/symbol/MethodSymbol.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/context/symbol/RegionSymbol.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/context/symbol/Symbol.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/context/symbol/VariableSymbol.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/providers/DocumentSymbolProvider.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/providers/SymbolProvider.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/providers/CodeActionProviderTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/providers/SymbolProviderTest.java

Реализация workspaceSymbol

---

build.gradle.kts

WIP latest msclasses

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CommonModuleNameCachedDiagnostic.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CommonModuleNameCachedDiagnosticTest.java

Опечатка ПовнорноеИспользование
Closes #1315
Closes:

ПовторноеИспользование typo

---

build.gradle.kts

new lib versions

---

.github/workflows/benchmark.yml
build.gradle.kts

Spring boot version bump
Closes:

spring boot 2.3.3

---

build.gradle.kts
src/main/java/com/github/_1c_syntax/bsl/languageserver/BSLLSBinding.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/BSLLSPLauncher.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/infrastructure/DiagnosticInfosConfiguration.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/infrastructure/DiagnosticsConfiguration.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/BSLLSBindingTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/SmokyTest.java

Поддержка включения бсл лс как библиотеки в другие проекты.
Closes:

BSL LS as library

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/BSLLSPLauncher.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/cli/AnalyzeCommand.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/cli/FormatCommand.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/cli/LanguageServerStartCommand.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/cli/VersionCommand.java

Добавлены спрятанные параметры для включения отладочных логов и переопределения пути к файлу конфигурации спринга.
Closes:

Возможность включения отладочных логов спринга

---

build.gradle.kts
gradle/wrapper/gradle-wrapper.properties

Deps upgrade

---

build.gradle.kts
src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/Trees.java

bsl-parser 0.15.1

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MetadataObjectNameLengthDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/Ranges.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MetadataObjectNameLengthDiagnosticTest.java

MetadataObjectNameLength
Теперь замечание вешается на токен с ренджом
Closes: #1366

MetadataObjectNameLengthDiagnostic  Замечание вешается на токен с ренджом

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/AbstractCommonModuleNameDiagnostic.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CommonModuleInvalidTypeDiagnosticTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CommonModuleNameCachedDiagnosticTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CommonModuleNameClientDiagnosticTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CommonModuleNameClientServerDiagnosticTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CommonModuleNameFullAccessDiagnosticTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CommonModuleNameGlobalClientDiagnosticTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CommonModuleNameGlobalDiagnosticTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CommonModuleNameServerCallDiagnosticTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CommonModuleNameWordsDiagnosticTest.java

comonModuleName вешаются на первый токен в файле
Closes: #1374

comonModuleName вешаются на первый токен в файле

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/AutoServerInfo.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/BSLLanguageServer.java
src/main/resources/application.properties
src/test/java/com/github/_1c_syntax/bsl/languageserver/AutoServerInfoTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/cli/VersionCommandTest.java

В ответ на запрос initialize добавлена информация о ServerInfo

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CodeOutOfRegionDiagnostic.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CodeOutOfRegionDiagnosticTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/providers/DocumentLinkProviderTest.java

Для диагностики CodeOutOfRegionDiagnostic добавлено игнорирование модуля с типом Unknown
Closes: #1386

Диагностика CodeOutOfRegionDiagnostic не реагирует на неизвестный модуль

---

src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CodeOutOfRegionDiagnosticTest.java

Рекомендации взял [здесь](https://groups.google.com/g/mockito/c/9WUvkhZUy90?pli=1)

Исправлено падение теста codeOutOfRegion на Ubuntu

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/codelenses/CodeLensSupplier.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/codelenses/CognitiveComplexityCodeLensSupplier.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/codelenses/CyclomaticComplexityCodeLensSupplier.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/codelenses/package-info.java

Помойка в провайдере разделена на интерфейс и два бина-сапплаера. 
Каждый сапплаер предоставляет свой вид код ленза.
Closes:

Рефакторинг CodeLensProvider

---

src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/DiagnosticsTest.java

Использование doReturn поверх spy

Исправление тестов

---

.idea/compiler.xml
.idea/misc.xml
build.gradle.kts
src/main/java/com/github/_1c_syntax/bsl/languageserver/cli/AnalyzeCommand.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/cli/FormatCommand.java

javadoc-links и junit оставлены старыми, т.к. при их бампе что-то все совсем радикально разваливается

Обновление зависимостей

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/BSLLanguageServer.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/BSLTextDocumentService.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/cli/AnalyzeCommand.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/cli/FormatCommand.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/context/DocumentContext.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/context/ServerContext.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/context/infrastructure/DocumentContextConfiguration.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/jsonrpc/Diagnostics.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/jsonrpc/ProtocolExtension.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/providers/DiagnosticProvider.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/BSLTextDocumentServiceTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/context/DocumentContextTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/context/ServerContextTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/context/computer/MethodSymbolComputerTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/UsingModalWindowsDiagnosticTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/util/TestUtils.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/util/assertions/CodeActionAssert.java

В DocumentContext добавлена версия. В DiagnosticProvider и ответ на x-diagnostics добавлен возврат версии
Closes: #1388

Хранение и учет версии документа

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/context/computer/MethodSymbolComputer.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/context/symbol/ParameterDefinition.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/context/computer/MethodSymbolComputerTest.java

Добавлено сохранение дефолтного значения параметра с информацией о типе (на основе данных дерева разбора) и строковом представлении параметра.
Closes: #1493

Расчет типа параметра

---

build.gradle.kts

Обновлена версия bsl-parser, в котом исправлена ошибка обработки удалить .. вставить
Closes: #1473

bump bsl-parser version

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/UsingHardcodeNetworkAddressDiagnostic.java

Эта диагностика занимает 2 место среди самых долгих диагностик.
моя правка небольшая
- вместо замены всех кавычек во всех строках избавляюсь только от крайних кавычек в строке
- максимально простая операция вместо сложной замены кавычек
в итоге все строки будут обрабатываться быстрее.
Closes: нет, ПР в честь празника )

Ускорение диагностики UsingHardcodeNetworkAddress - упрощена обработка строк

---

build.gradle.kts

fixes https://github.com/qoomon/gradle-git-versioning-plugin/issues/13

build: fix git-versioning config

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/context/symbol/SymbolTree.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/hover/VariableSymbolMarkupContentBuilderTest.java

Добавлен метод поиска VariableSymbol по имени и области объявления.
Closes:

Расширение символьного апи для поиска переменной с учетом области объявления

---

build.gradle.kts
src/main/java/com/github/_1c_syntax/bsl/languageserver/BSLLanguageServer.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/DocumentSelector.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/providers/DocumentSymbolProvider.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/BSLLanguageServerTest.java

Переезд обратно на официальный lsp4j.
Уточнение параметров регистрации сервера - использование соответствующих *Options для каждого провайдера.
Closes:

Апгрейд до LSP 0.11.0 и уточнение capabilities сервера

---

build.gradle.kts

bump mdclasses version
Closes:

bump mdclasses version

---

build.gradle.kts

Обновлена версия BSL-Parser 
Closes:

bump bsl-parser version: 0.18.0

---

docs/assets/stylesheets/extra.css
mkdocs.en.yml
mkdocs.yml

- Заменя иконок переключения на лампочки
- Смена фона шапки с контрастного черного на темно-темно-серый
- Замена акцентного цвета ссылок с индиго на светло-голубой
- Инвертация цвета логотипа

fix: Ночная тема

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndex.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceResolver.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceResolverTest.java

Убрал использование ReferenceResolver в ReferenceIndex

Удаление циклической зависимости на ReferenceResolver

---

build.gradle.kts

Bsl parser bump

---

build.gradle.kts
lombok.config

Внешние ссылки на javadoc от mdclasses

---

build.gradle.kts
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/FullOuterJoinQueryDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/IncorrectUseLikeInQueryDiagnostic.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/UnionAllDiagnostic.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/FullOuterJoinQueryDiagnosticTest.java

Обновлен BSL Parser до pre-0.20.0
Closes:

parser bump

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/IncorrectUseLikeInQueryDiagnostic.java

IncorrectUseLikeInQuery Важность Major, а не Critical
#1648

IncorrectUseLikeInQuery Важность Major, а не Critical

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/UsingLikeInQueryDiagnostic.java

Исправил - Важность Major вместо Critical
#1648

UsingLikeInQuery - Важность Major вместо Critical

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/VirtualTableCallWithoutParametersDiagnostic.java

VirtualTableCallWithoutParameters - Важность Major вместо Critical
#1648

VirtualTableCallWithoutParameters - Важность Major вместо Critical

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/AllFunctionPathMustHaveReturnDiagnostic.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/AllFunctionPathMustHaveReturnDiagnosticTest.java

Для диагностики AllFunctionPathMustHaveReturnDiagnostic отключен режим анализа препроцессорных условий
Сloses #1774

Быстрый фикс для #1774. 

---

build.gradle.kts
src/test/java/com/github/_1c_syntax/bsl/languageserver/codeactions/DisableDiagnosticTriggeringSupplierTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/documentlink/DiagnosticDescriptionDocumentLinkSupplierTest.java

В новой версии LT английский язык больше не кидает замечаний на русские слова, поэтому для английских вариантов тестов исключены некоторые срабатывания typo
Closes

Обновлен LanguageTool

---

docs/en/reporters/sarif.md

@nixel2007 
Файл переведен отдельно. У crowdin сломался интерфейс на переводе длинных строк.

docs: перевод sarif-reporter на англ.. Блок fullDescription в примере упрощен и переведен.

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/hover/MethodSymbolMarkupContentBuilder.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/hover/VariableSymbolMarkupContentBuilder.java
src/main/resources/com/github/_1c_syntax/bsl/languageserver/hover/MethodSymbolMarkupContentBuilder_en.properties
src/main/resources/com/github/_1c_syntax/bsl/languageserver/hover/MethodSymbolMarkupContentBuilder_ru.properties
src/main/resources/com/github/_1c_syntax/bsl/languageserver/hover/VariableSymbolMarkupContentBuilder_en.properties
src/main/resources/com/github/_1c_syntax/bsl/languageserver/hover/VariableSymbolMarkupContentBuilder_ru.properties
src/test/java/com/github/_1c_syntax/bsl/languageserver/hover/MethodSymbolMarkupContentBuilderTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/hover/VariableSymbolMarkupContentBuilderTest.java

Убран префикс местоположения, mdoRef превращен в маркдаун-гиперссылку с указанием URI и номера строки. Работа проверена в vscode и sublime text 4
Closes #1802

Гиперссылка в местоположении символа, ведущая на файл и номер строки

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/WrongDataPathForFormElementsDiagnostic.java

fix NPE WrongDataPathForFormElementsDiagnostic
Closes #1899

fix NPE WrongDataPathForFormElementsDiagnostic

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/UsingSynchronousCallsDiagnostic.java

Перевел на использование описания метода 
Closes: #1864

Оптимизация UsingSynchronousCallsDiagnostic

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/context/DocumentContext.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/context/ServerContext.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFiller.java

Грязно, ужасно, пока не смотреть :)
Closes

Сохранение неизменяемых между populateContext и rebuild данными в DocumentContext.

---

.github/workflows/codeql-analysis.yml
.github/workflows/gradle.yml
.github/workflows/javadoc.yml
.github/workflows/qa.yml

Отключение задач GA для переводов
Closes

Отключение задач GA для переводов

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/DataExchangeLoadingDiagnostic.java

упрощен код диагностики, повышена читаемость, убран Fixme
Closes 
Должна была закрываться #1781 но увы

refactor: упрощен код диагностики, повышена читаемость

---

build.gradle.kts
src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/expressiontree/ExpressionTreeBuildingVisitor.java

Обновление bsl-parser до последней dev-версии
Closes

Обновление bsl-parser до последней dev-версии

---

build.gradle.kts
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/FieldsFromJoinsWithoutIsNullDiagnostic.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/QueryParseErrorDiagnosticTest.java

bslparser обновлене до 0.21.0
Closes

bump bslparser -> 0.21.0

---

.github/workflows/qa.yml

Secure qa run

---

src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/UnusedLocalVariableDiagnostic_ru.properties

UnusedLocalVariable - Исправлена опечатка в сообщении правила

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/references/model/SymbolOccurrence.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/Ranges.java

сделал для 
- SymbolOccurrence
спец.методы сравнения в Trees
- Range
- Position
Closes 
- договоренность @nixel2007

Натуральный порядок сравнения ссылок на символы, а также сравнение Range, Position

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/context/ServerContext.java

Исправлена проблема однопоточного чтения конфигурации

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/ParentProcessWatcher.java

Что бы закрытие не пыталось слаться в centry и не пыталось спрашивать слать или нет
Closes

Понизил уровень ошибки

---

build.gradle.kts

bump version bslls-dev-tool
Closes

Обновление версии плагина

---

.github/scripts/build-jpackage.py
.github/workflows/gradle.yml
.github/workflows/release.yml

Closed: #2919 
**Проблема:**
Неправильная подпись приложения под macOS Ventura, система считаем приложение поврежденным.
**Решение:**
Сборка приложения под macOS, использую j20. В этой версии проблема исправлена.

fix(build): Поддержка jpackage macOS Ventura

---

.github/workflows/check-package.yml
build.gradle.kts

Проверка сборки package в develop + поддержка jdk20 для jacoco и lombok

---

build.gradle.kts

Попытка указания constraint для guava

---

build.gradle.kts
src/main/java/com/github/_1c_syntax/bsl/languageserver/BSLTextDocumentService.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/BSLWorkspaceService.java

Lsp4j 0.21.0

---

lombok.config
src/main/java/com/github/_1c_syntax/bsl/languageserver/providers/InlayHintProvider.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/reporters/ReportersAggregator.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/providers/InlayHintProviderTest.java

Исправлено внедрение списка включенных сапплаеров

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/codelenses/RunAllTestsCodeLensSupplier.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/codelenses/RunTestCodeLensSupplier.java

Исправлена ошибка указания идентификатор линз запуска тестов
Closes

Исправлена ошибка указания идентификатор линз запуска тестов

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/context/computer/DiagnosticComputer.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingCommonModuleMethodDiagnostic.java

Исправлена ошибка падения анализа из-за исключения выпадающего из MissingCommonModuleMethodDiagnostic
Closes #3064

Исправлена ошибка падения анализа из-за исключения выпадающего из MissingCommonModuleMethodDiagnostic

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/RefOveruseDiagnostic.java

Nullable jsr305

---

build.gradle.kts

Spring boot 3.1

---

.github/workflows/qodana.yml

Qodana portal

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/AnalyzeProjectOnStart.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/BSLLanguageServer.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/BSLTextDocumentService.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/BSLWorkspaceService.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/context/ServerContext.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/context/computer/DiagnosticComputer.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/NamedForkJoinWorkerThreadFactory.java

Вынос тяжелых parallelStream в отдельный пул потоков, больше именованных пулов

---

build.gradle.kts
src/main/resources/com/github/_1c_syntax/bsl/languageserver/configuration/parameters-schema.json
src/main/resources/com/github/_1c_syntax/bsl/languageserver/configuration/schema.json

Недостающие ключи диагностик
Closes

schema.json fix

---

build.gradle.kts

Релизный парсер

---

build.gradle.kts

Обновление версии bsl-parser до 0.23
Closes

bsl-parser 0.23

---

.gitignore
build.gradle.kts

Обновлены зависимости

---

build.gradle.kts

mdclasses 0.13

---

build.gradle.kts
src/main/resources/com/github/_1c_syntax/bsl/languageserver/configuration/parameters-schema.json
src/main/resources/com/github/_1c_syntax/bsl/languageserver/configuration/schema.json
src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/FileSystemAccessDiagnostic_en.properties

- новая версия плагина
- исправления в схемах и доках
Closes

Новая версия BSLLS-DEV-TOOLS

---

qodana.yaml

Явное указание linter для qodana

---

build.gradle.kts

Обновление для исправления ошибки создания новых диагностик
Closes

new bslls-dev-tools

---

.github/workflows/check-package.yml
.github/workflows/gradle.yml
.github/workflows/release.yml

Сборка на jdk23

---

build.gradle.kts

Jacoco bump

---

build.gradle.kts

Drop lombok and jacoco implicit versions

---

build.gradle.kts
docs/en/diagnostics/DoubleNegatives.md

обновление версии mdclasses
Closes

обновление версии mdclasses

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/configuration/codelens/TestRunnerAdapterOptions.java
src/main/resources/com/github/_1c_syntax/bsl/languageserver/configuration/schema.json

Поиск тестов через бсл лс выключен по умолчанию

---

src/main/java/com/github/_1c_syntax/bsl/languageserver/aop/sentry/SentryScopeConfigurer.java

Исправлен пропуск вопроса перед отправкой в Sentry

---

build.gradle.kts
src/test/java/com/github/_1c_syntax/bsl/languageserver/AnalyzeProjectOnStartTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/cli/VersionCommandTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/cli/WebsocketCommandTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/commands/ToggleCognitiveComplexityInlayHintsCommandSupplierTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/commands/ToggleCyclomaticComplexityInlayHintsCommandSupplierTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/UsingModalWindowsDiagnosticTest.java
src/test/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexReferenceFinderTest.java

Обновление зависимостей, перевод deprecated mockito аннотаций на новые

---

build.gradle.kts
src/main/java/com/github/_1c_syntax/bsl/languageserver/BSLLSBinding.java
src/main/java/com/github/_1c_syntax/bsl/languageserver/infrastructure/CacheConfiguration.java
src/main/resources/application.properties

Добавлено явное определение конфигурации кэширования с использованием caffeine
Closes

Добавлено кэширование caffeine
