1c-syntax/bsl-language-server

- src/main/java/org/github/_1c_syntax/bsl/languageserver/cli/AnalyzeCommand.java
- src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/AnalysisInfo.java
- src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/JUnitReporter.java
- src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/JUnitTestSuites.java
- src/test/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/ConsoleReporterTest.java
- src/test/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/GenericReporterTest.java
- src/test/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/JUnitReporterTest.java
- src/test/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/JsonReporterTest.java
- src/test/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/ReportersAggregatorTest.java
- src/test/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/TSLintReporterTest.java
#351
Поправил формирование отчета в формате junit
- убрал множественные failure
- поправил имена атрибутов
- Скорректировал имена файлов - теперь используются относительные
Добавил в класс AnalysisInfo sourceDir - каталог с исходниками. По умолчанию это текущий каталог. Добавлен проброс из cli каталога исходников в AnalysisInfo
> Доработка репортера для junit 

- src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/OneStatementPerLineDiagnostic.java
- src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/OneStatementPerLineDiagnosticTest.java
- src/test/resources/diagnostics/OneStatementPerLineDiagnostic.bsl
Пропуск диагностики OneStatementPerLine при ошибке разбора
Closes: #630
> OnestatementPerLine fp fix

- src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/DiagnosticStorage.java
Не вешать диагностику на ноды с ошибкой разбора.
Позволит не только избежать рандомных падений на сонаре, но и уберет лишние срабатывания в линтере при наборе текста.
Closes: #632
> Не вешать диагностику на ноды с ошибкой разбора.

- src/main/java/com/github/_1c_syntax/bsl/languageserver/cli/AnalyzeCommand.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/FileInfo.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/GenericIssueReport.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/JUnitTestSuites.java
- src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/ConsoleReporterTest.java
- src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/GenericReporterTest.java
- src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/JUnitReporterTest.java
- src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/JsonReporterTest.java
- src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/ReportersAggregatorTest.java
- src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/TSLintReporterTest.java
FileInfo теперь хранит относительный путь. Путь строится относительно параметра sourceDir.
Closes: #633
> Перевод fileinfo на относительные пути

- src/main/java/com/github/_1c_syntax/bsl/languageserver/context/DocumentContext.java
- src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/EmptyRegionDiagnosticTest.java
- src/test/java/com/github/_1c_syntax/bsl/languageserver/util/assertions/CodeActionAssert.java
* Исправил assertThat.of().in().fixes() - после применения qf удаляла из контента все переносы строк
* Вызов assertThat.of().in().fixes() модифицировал documentContext из-за чего повторная попытка работа с ним приводила в к ошибкам в рантайме или неверным значениям
* Добавил более внятное сообщение об ошибке для documentContext.getText() если range выходит за края разбираемого документа
WIP так как есть еще ряд моментов, которые хочется проверить.
Closes: #764
> Fix quick fix assert that fixes

- src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/GenericCoverageReport.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/GenericCoverageReporter.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/ReportersAggregator.java
- src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/reporter/GenericCoverageTest.java
Добавлена возможность по выводу в отчет строк требующих покрытия в формате GenericCoverage
Closes #1105
> Добавлена возможность по выводу в отчет строк требующих покрытия

- src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/FunctionShouldHaveReturnDiagnostic.java
FunctionShouldHaveReturn перенос проверки разбора после диагностики.
Незначительный прирост: Стало - 759, Было -1108
Closes:
> FunctionShouldHaveReturn перенос проверки разбора

- src/main/java/com/github/_1c_syntax/bsl/languageserver/context/ServerContext.java
Запрос конфигурации впервые выполняется внутри параллельного стрима. Метаданные внутри тоже используют параллельные стримы. Из-за исчерпания свободных потоков (все потоки, кроме текущего, висят на ожидании расчета конфигурации) метаданные рассчитываются в одном потоке. Переопределение тред-пула развязывает параллелизацию метаданных и сбора контекста
> Расчет метаданных в отдельном тред-пуле

- src/main/java/com/github/_1c_syntax/bsl/languageserver/BSLLanguageServer.java
Fix #1432 
Пока сделано напрямую в инициализации лэнг-сервера. В последствии если на стороне прикладного ЛС потребуется переопределение (например, модели синхронизации, или поддержки willSave), можно будет выделить в отдельный бин либо options целиком, либо каждое из его свойств
> Использование более актуального TextDocumentSyncOptions в initialize

- src/main/java/com/github/_1c_syntax/bsl/languageserver/providers/CodeActionProvider.java
- src/test/java/com/github/_1c_syntax/bsl/languageserver/providers/CodeActionProviderTest.java
Добавлено заполнение поля isPreferred для квик-фиксов, исправляющих одну диагностику.
Исправлена фильтрация код экшенов при передаче отбора only
Closes: #1434
Fixes: #1375
> Расширение API диагностик - isPreferred и фильтр по типам код экшенов

- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- src/main/java/com/github/_1c_syntax/bsl/languageserver/context/symbol/Symbol.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/providers/DocumentSymbolProvider.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/providers/SymbolProvider.java
- src/test/java/com/github/_1c_syntax/bsl/languageserver/providers/DocumentSymbolProviderTest.java
- src/test/java/com/github/_1c_syntax/bsl/languageserver/providers/SymbolProviderTest.java
Spring Boot, JUnit и Javadoc оставлены на потом.
Бамп спринг-бута замедляет анализ на 15%, бамп junit без спрингбута роняет тесты (конфликты зависимостей), новый javadoc не собирается из-за несовместимости с котлином 1.4
Closes #1486
> lsp4j 0.10.0 + обновление зависимостей

- src/main/java/com/github/_1c_syntax/bsl/languageserver/context/computer/MethodSymbolComputer.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/context/computer/RegionSymbolComputer.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/context/computer/SymbolTreeComputer.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/context/computer/VariableSymbolComputer.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/context/symbol/LocatableSymbol.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/context/symbol/MethodSymbol.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/context/symbol/RegionSymbol.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/context/symbol/SourceDefinedSymbol.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/context/symbol/Symbol.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/context/symbol/SymbolTree.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/context/symbol/VariableSymbol.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/AbstractSymbolTreeDiagnostic.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/providers/DocumentSymbolProvider.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/providers/SymbolProvider.java
Из интерфейса Symbol выделены куски, отвечающие за место определения символа - юри и рэнж. Введено понятие selectionRange для определения "места интереса" для данного символа.
В последствии интерфейс Symbol может быть использован как более общее понятие для чего-то, находящегося в документе, например, вызов метода глобального контекста, или стандартного метода объекта. В противовес этому SourceDefinedSymbol - это символ, у которого есть явное местоположение в исходном коде.
> Выделение SourceDefinedSymbol из интерфейса Symbol

- src/main/java/com/github/_1c_syntax/bsl/languageserver/context/computer/MethodSymbolComputer.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/context/computer/RegionSymbolComputer.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/context/computer/SymbolTreeComputer.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/context/computer/VariableSymbolComputer.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/context/symbol/MethodSymbol.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/context/symbol/RegionSymbol.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/context/symbol/SourceDefinedSymbol.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/context/symbol/VariableSymbol.java
- src/test/java/com/github/_1c_syntax/bsl/languageserver/context/computer/MethodSymbolComputerTest.java
uri заменен на owner для упрощения получения информации о владельце символа.
На текущий момент все SourceDefinedSymbol строятся по DocumentContext, соответственно, владелец символа однозначно может быть определен не просто как URI, но и как DocumentContext
> Добавление owner в SourceDefinedSymbol

- .github/workflows/gh-pages.yml
- docs/assets/javascripts/tables.js
- docs/assets/stylesheets/extra.css
- mkdocs.en.yml
- mkdocs.yml
1. Теперь светлая или темная тема подъезжает в рамках параметров хрома (или винды)
2. Оглавление теперь отображается инлайн в содержании
3. Для нормального отображения пришлось сделать главное меню табами
4. Вроде б починился поиск. Раньше он работал хреного
5. Якоря на оглавления теперь генерируются с учетом кириллицы
6. В таблицах теперь есть сортировка при клике по заголовку
Посмотреть изменения можно тут:
- https://stepa86.github.io/bsl-language-server/dev/
- https://stepa86.github.io/bsl-language-server/dev/en/
> Обновление сайта после обновлений mkdocs-material

- build.gradle.kts
- src/main/java/com/github/_1c_syntax/bsl/languageserver/codeactions/AbstractQuickFixSupplier.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/codeactions/FixAllCodeActionSupplier.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/codeactions/QuickFixSupplier.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/metadata/DiagnosticCode.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/reporters/JUnitTestSuites.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/reporters/databind/DiagnosticCodeSerializer.java
Наткнулся на https://github.com/eclipse/lsp4j/issues/478 при локальной отладке.
Исправление - в еще не вышедшем lsp4j 0.11.0, поэтому временно перевел сборку на jitpack.io
> Адаптация к грядущему релизу lsp4j 0.11.0, исправление инициализации запроса на rename

- src/main/java/com/github/_1c_syntax/bsl/languageserver/codeactions/DisableDiagnosticTriggeringSupplier.java
- src/test/java/com/github/_1c_syntax/bsl/languageserver/codeactions/DisableDiagnosticTriggeringSupplierTest.java
Исправлено падение кодэкшнпровайдера на не bsl ls диагностиках
Closes: #1517
> Падает код экшн провайдера fix #1517

- src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/UsingHardcodePathDiagnostic.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/UsingHardcodeSecretInformationDiagnostic.java
- UsingHardcodePath
- UsingHardcodeSecretInformation
- вместо замены всех кавычек во всех строках избавляюсь только от крайних кавычек
Ускорение аналогично принятому ПР https://github.com/1c-syntax/bsl-language-server/pull/1565
Closes:-
> Ускорение 2 диагностик - UsingHardcodePath и UsingHardcodeSecretInformation - убрал замену всех кавычек на удаление крайних кавычек

- build.gradle.kts
Вместо явного пакетирования зависимостей в pom.xml используется плагин для gradle.
Отключена генерация gradle metadata, т.к. она конфликтует с spring dependency managament plugin.
Closes: #1618
> Исправление публикации информации о зависимостях bsl ls в режиме подключения как библиотеки

- src/main/java/com/github/_1c_syntax/bsl/languageserver/ParentProcessWatcher.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/aop/EventPublisherAspect.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/aop/Pointcuts.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/events/LanguageServerInitializeRequestReceivedEvent.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/events/package-info.java
- src/test/java/com/github/_1c_syntax/bsl/languageserver/ParentProcessWatcherTest.java
Добавлено фоновое задание, периодически проверяющее, что процесс, стартовавший сервер, все еще жив. Данные о процессе берутся из initialize-запроса:
https://microsoft.github.io/language-server-protocol/specifications/specification-current/#initialize
Вотчер будет отслеживать наличие процесса с pid равным processId.
Коммуникация между вотчером и BSLLanguageServer реализована посредством Events API для исключения циклических зависимостей между вотчером и сервером.
Closes:
> Отслеживание смерти родительского процесса

- gradle.properties
По умолчанию metaspace для градль-процесса ограничивается 256 мегабайтами.
https://docs.gradle.org/current/userguide/build_environment.html#sec:configuring_jvm_memory
> Установка повышенного размера metaspace для работы шага QA

- docs/en/diagnostics/UsageWriteLogEvent.md
- docs/en/diagnostics/index.md
- src/main/resources/com/github/_1c_syntax/bsl/languageserver/configuration/parameters-schema.json
- src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/UsageWriteLogEventDiagnostic_en.properties
Описание диагностики UsageWriteLogEvent на английском языке — «Incorrect use of the method». Оно не вполне информативно, так как не содержит названия конкретного метода. На русском всё в порядке — «Неверное использование метода "ЗаписьЖурналаРегистрации"».
Добавил имя метода в строку лэнгпаке диагностики UsageWriteLogEvent для английского языка. Остальные файлы, включенные в PR (документация, параметры диагностик), были изменены автоматически при сборке.
Closes #1896
Пункт «Изменения покрыты тестами» проставлен (т.к. был рассмотрен), но по факту покрывать этот коммит тестами выглядит избыточным. Кроме того, не вполне понятно, как должен выглядеть такой тест.
Мне кажется, имеет смысл опустить.
> Информативное наименование диагностики UsageWriteLogEvent на английском языке

- src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/RedundantAccessToObjectDiagnostic.java
- src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/RedundantAccessToObjectDiagnosticTest.java
RedundantAccessToObject разрешать обращение по имени в модулях повтИсп
Closes #1546
> RedundantAccessToObject разрешать обращение по имени в модулях повтИсп

- src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFiller.java
- src/test/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFillerTest.java
При обращении к свойствам переменных в референс индекс попадало значение
области имени переменной вмести с именем свойства.
Из-за этого в VSCode при наведении на свойство отображалась подсказка
для переменной.
Сейчас в область попадает только имя переменной.
Closes #2743 2743
> Исправлен расчет облости имени переменной при обращении к ее свойству

- src/main/java/com/github/_1c_syntax/bsl/languageserver/references/model/Symbol.java
контракт "x.compareTo(…y)) == -signum(y.compareTo(x))" не выполняется при сравнении объектов с одинаковым hashcode
> fix: исправлено нарушение контракта compareTo

- src/main/java/com/github/_1c_syntax/bsl/languageserver/cli/FormatCommand.java
- src/test/java/com/github/_1c_syntax/bsl/languageserver/BSLLSPLauncherTest.java
Добавлена возможность форматировать несколько файлов/директорий…одновременно. дополнительные элементы перечисляются через запятую
Параметр srcDir команды форматтера теперь разбивает значение по запятым
Close #1942
> Доработка форматтера

- src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFiller.java
из репо 1с-синтакс
Исправлено падение анализа на БСП 3.1
- ![image](https://user-images.githubusercontent.com/2920817/179393954-571f5ac1-6275-4c0a-99c3-94f48e83f2f7.png)
- .
- 
Closes
> исправлено падение анализа на БСП 3.1 из-за ошибки в RefefernceIndexFiller

- build.gradle.kts
- src/main/java/com/github/_1c_syntax/bsl/languageserver/configuration/LanguageServerConfiguration.java
1. Поднята версия спринга
2. Добавлены дефолтные значения Value аннотаций, чтобы предотвратить падение при старте сонара
> Поднятие зависимости спринга

- src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/FieldsFromJoinsWithoutIsNullDiagnostic.java
- src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/FieldsFromJoinsWithoutIsNullDiagnosticTest.java
- Восстановление правила FieldsFromJoinsWithoutIsNull после изменения парсера запросов 
- убран признак Disabled
- кратко документирован алгоритм
Closes #2900
Фактически исправил одно выражение 
- `private static final Integer WHERE_ROOT = SDBLParser.RULE_query;`
> Восстановление правила FieldsFromJoinsWithoutIsNull после изменения парсера запросов 

- src/main/java/com/github/_1c_syntax/bsl/languageserver/inlayhints/SourceDefinedMethodCallInlayHintSupplier.java
- src/test/java/com/github/_1c_syntax/bsl/languageserver/configuration/LanguageServerConfigurationTest.java
- src/test/java/com/github/_1c_syntax/bsl/languageserver/inlayhints/SourceDefinedMethodCallInlayHintSupplierTest.java
- src/test/resources/.partial-bsl-language-server.json
1. Исправлена ошибка чтения параметров SourceDefinedMethodCallInlayHintSupplier теперь ищет настройки в параметрах inlayHint а не CodeLens
2. Добавлен тест на параметр showParametersWithTheSameName для SourceDefinedMethodCallInlayHintSupplier
3. Добавлен тест на чтение параметров inlayHints в конфигурации.
Closes #3063
> Исправлена ошибка чтения параметров SourceDefinedMethodCallInlayHintSupplier

- build.gradle.kts
Эта зависимость выкидывает выхлоп на старте
```
Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
```
Из-за которого рушится плагин в vsc и не может подключиться.
> Исключил commons-logging.

- src/main/java/com/github/_1c_syntax/bsl/languageserver/BSLLanguageServer.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/BSLTextDocumentService.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/BSLWorkspaceService.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/aop/SentryAspect.java
Добавлена передача cachedThreadPool в методы всех сервисов, использующих supplyAsync. See #3104.
Не уверен насчет дедлоков, но ховер стал отвечать намного-намного быстрее, не дожидаясь конца расчета конфигурации (проверял на УХе)
Closes #3104
> Передача executor service во все сервисы

- src/main/java/com/github/_1c_syntax/bsl/languageserver/BSLLSPLauncher.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/context/computer/DiagnosticComputer.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/infrastructure/LanguageClientAwareAppender.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/infrastructure/LanguageClientAwareAppenderConfiguration.java
- src/main/java/com/github/_1c_syntax/bsl/languageserver/infrastructure/LogbackConfiguration.java
- src/main/resources/language-client-aware-appender.xml
- src/main/resources/logback-spring.xml
> Аппендер вывода логов в LanguageClient, если он подключен

- src/main/java/com/github/_1c_syntax/bsl/languageserver/context/DocumentContext.java
Т.к. он используется как ключ Map, класс обязан имплементировать Comparable
Closes
> DocumentContext сделан Comparable

- build.gradle.kts
- jitpack.yml
- src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/RewriteMethodParameterDiagnostic.java
Обновлены зависимости,теперь используется собственная библиотека ANTLR  
Closes
> Обновление на новый парсер с antlr 4.13.1

- src/main/java/com/github/_1c_syntax/bsl/languageserver/aop/SentryAspect.java
- src/main/resources/com/github/_1c_syntax/bsl/languageserver/aop/SentryAspect_en.properties
- src/main/resources/com/github/_1c_syntax/bsl/languageserver/aop/SentryAspect_ru.properties
> Sentry ID отправляется для показа клиенту

- src/main/java/com/github/_1c_syntax/bsl/languageserver/aop/sentry/SentryScopeConfigurer.java
> Хэширование имени хоста и отправка в Sentry, фильтрация стак трейса по принадлежности к приложению
